
{
    'name': 'Pos Quotations',
    'version': '15.0.1.0.3',
    'category': 'Sales/Point of Sale',
    'sequence': 6,
    'license': 'LGPL-3',
    'summary': 'Create Quotation, Save Quotation and Load Quotation Order in Point Of Sale (Pos). Pos order Pos Note for quotation order',
    'description': """
        pos quotation,
        pos_quotation,
        pos load quotation,
        pos save quotation,
        pos create quotation,
        pos order,
        pos_order_quotation,
        pos_order,
        POS Quotation,
        pos load order,
        POS Quotations,
        point of sale,
        pos save quotation,
        pos load quotation,
        pos order quotation,
        AB Tech,
        Quotation,
        Quotations,
        pos,
        pos_order_quotation,
        pos_load_quotation,
        pos_save_quotation,
        """,
    'author': "AB Tech",
    'website': 'abtechsolution.in',
    'depends': ['point_of_sale'],
    'contributors': [
        'David Rodrigues <davd.lza@hotmail.com>',
    ],
    'data': [
        'security/ir.model.access.csv',
        # 'views/assests.xml',
        'views/pos_quotation.xml',
        'data/ir_sequence.xml',
        'views/pos_order.xml',
    ],
    'assets': {
        'point_of_sale.assets': [
            'hm_pos_order_quotation/static/src/js/**/*',
            
        ],
        'web.assets_qweb': [
            'hm_pos_order_quotation/static/src/xml/**/*',
        ],
        # 'web.assets_backend': [
        #     'om_account_asset/static/src/scss/account_asset.scss',
        #     'om_account_asset/static/src/js/account_asset.js',
        # ],
    },
    # 'qweb': [
    #     'static/src/xml/LoadQuotationButton.xml',
    #     'static/src/xml/CreateQuotationButton.xml',
    #     'static/src/xml/SaveQuotationPopUp.xml',
    #     'static/src/xml/LoadQuotationPopup.xml',
    #     'static/src/xml/OrderReceipt.xml',
    #     'static/src/xml/AlertPopups.xml',
    # ],
    "images": ["static/description/banner.gif"],
    'installable': True,
}
